# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3'

services:
  ps: # PostgreSQL service
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_DB: gatewaydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak_container
    command: ['start-dev --import-realm']

    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db_container
      DB_PORT: 5432
      DB_DATABASE: gatewaydb
      DB_USER: admin
      DB_PASSWORD:
        admin
        # Other environment variables...
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 9443
      KC_HEALTH_ENABLED: true
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
